version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: judge/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    restart: always
    
    mem_limit: 512m          
    cpus: '0.5'             
    network_mode: "bridge"   