# Generated by Django 6.0.8 on 2026-08-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
    ]
