# Generated by Django 6.0.8 on 2026-08-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20260808_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='statement',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='editorial',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='hints',
        ),
        migrations.AddField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='hidden_test_cases',
            field=models.TextField(blank=True, help_text='Format test cases securely for backend evaluation', null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated tags, e.g., Array, Math, String', max_length=200, null=True),
        ),
    ]
