# Generated by Django 6.0.8 on 2026-08-09 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_rename_statement_problem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='constraints',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='hidden_test_cases',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='sample_input',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='sample_output',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rank',
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(default='Easy', max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='judge.problem'),
        ),
    ]
