# Generated by Django 6.0.8 on 2026-08-09 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_remove_problem_constraints_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('participants', models.ManyToManyField(blank=True, related_name='joined_contests', to=settings.AUTH_USER_MODEL)),
                ('problems', models.ManyToManyField(related_name='contests', to='judge.problem')),
            ],
        ),
    ]
