# Generated by Django 6.0.8 on 2026-08-09 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0006_badge_userprofile_last_active_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('python_code', models.TextField(blank=True, null=True)),
                ('cpp_code', models.TextField(blank=True, null=True)),
                ('time_complexity', models.CharField(default='O(N)', max_length=100)),
                ('space_complexity', models.CharField(default='O(1)', max_length=100)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editorial', to='judge.problem')),
            ],
        ),
    ]
