# Generated by Django 6.0.8 on 2026-08-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0008_discussion_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='participants',
        ),
        migrations.AlterField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='contests', to='judge.problem'),
        ),
    ]
