# Generated by Django 6.0.8 on 2026-08-10 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0009_remove_contest_participants_alter_contest_problems'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating_contests', to=settings.AUTH_USER_MODEL),
        ),
    ]
