# Generated by Django 6.0.8 on 2026-08-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0010_contest_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='space_complexity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_complexity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
