# Generated by Django 6.0.8 on 2026-08-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0013_userprofile_title_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
