# Generated by Django 6.0.8 on 2026-08-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0015_alter_problem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
