# Generated by Django 6.0.8 on 2026-08-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0020_rename_body_comment_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='company_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
