# Generated by Django 6.0.8 on 2026-08-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0021_problem_company_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_submission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
