# Generated by Django 6.1 on 2026-08-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0026_roadmap_roadmapstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(db_index=True, default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
